services:
  php:
    build: .
    image: php-8.3-fpm
    container_name: php
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - my-network
    command: ["sh", "-c", "composer install && tail -f /dev/null"]

volumes:
  mysql-data:
  mysql-logs:

networks:
  my-network:
    driver: bridge
